### ISSUE TITLE
Cloudflare still blocking unfortunately

### ISSUE THREAD

**Issue by daninger4995** [azoff/tockstalk#4]
Thanks for sharing this azoff. Unfortunately I have tried to circumvent the cloudflare block but it's behind the scenes. I keep getting 403 errors even when switching the browser used to chrome.  I will paste the error below, curious if you have any ideas to fix this.

` Running:  book-reservation.cy.ts                                                          (1 of 1)

  book reservation
    1) for first available time preference

  0 passing (2s)
  1 failing

  1) book reservation
       for first available time preference:
     CypressError: `cy.request()` failed on:

https://www.exploretock.com/login

The response we received from your web server was:

  > 403: Forbidden

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://www.exploretock.com/login
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/122.0.6261.69 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 403 - Forbidden
Headers: {
  "date": "Sun, 25 Feb 2024 22:10:00 GMT",
  "content-type": "text/html; charset=UTF-8",
  "transfer-encoding": "chunked",
  "connection": "close",
  "accept-ch": "Sec-CH-UA-Bitness, Sec-CH-UA-Arch, Sec-CH-UA-Full-Version, Sec-CH-UA-Mobile, Sec-CH-UA-Model, Sec-CH-UA-Platform-Version, Sec-CH-UA-Full-Version-List, Sec-CH-UA-Platform, Sec-CH-UA, UA-Bitness, UA-Arch, UA-Full-Version, UA-Mobile, UA-Model, UA-Platform-Version, UA-Platform, UA",
  "cross-origin-embedder-policy": "require-corp",
  "cross-origin-opener-policy": "same-origin",
  "cross-origin-resource-policy": "same-origin",
  "origin-agent-cluster": "?1",
  "permissions-policy": "accelerometer=(),autoplay=(),browsing-topics=(),camera=(),clipboard-read=(),clipboard-write=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()",
  "referrer-policy": "same-origin",
  "x-frame-options": "SAMEORIGIN",
  "cf-mitigated": "challenge",
  "cache-control": "private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0",
  "expires": "Thu, 01 Jan 1970 00:00:01 GMT",
  "set-cookie": [
    "__cf_bm=CZmwOEjLyoJ2pGJRyytgT8h1vzeEh7_noAPKnCjxz7s-1708899000-1.0-Ab+JjmAQYyrZyiaOOZwxv7GPpf0pWBu92fGVqBdNXKefQCxpovck+RRqNkzPvw750/OuXpC99egudmstY1wxGi8=; path=/; expires=Sun, 25-Feb-24 22:40:00 GMT; domain=.exploretock.com; HttpOnly; Secure; SameSite=None"
  ],
  "vary": "Accept-Encoding",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
  "x-content-type-options": "nosniff",
  "server": "cloudflare",
  "cf-ray": "85b3469f3d9ddb62-LAX",
  "content-encoding": "gzip",
  "alt-svc": "h3=\":443\"; ma=86400"
}
Body: <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1"><style>*{box-sizing:border-box;margin:0;padding:0}html{line-height:1.15;-webkit-text-size-adjust:100%;color:#313131}button,html{font-family:system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji}@media (prefers-color-scheme:dark){body{background-color:#222;color:#d9d9d9}body a{color:#fff}body a:hover{color:#ee730a;text-decoration:underline}body .lds-ring div{border-color:#999 transparent transparent}body .font-red{color:#b20f03}body .big-button,body .pow-button{background-color:#4693ff;color:#1d1d1d}body #challenge-success-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSIgdmlld0JveD0iMCAwIDI2IDI2Ij48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJNMTMgMGExMyAxMyAwIDEgMCAwIDI2IDEzIDEzIDAgMCAwIDAtMjZtMCAyNGExMSAxMSAwIDEgMSAwLTIyIDExIDExIDAgMCAxIDAgMjIiLz48cGF0aCBmaWxsPSIjZDlkOWQ5IiBkPSJtMTAuOTU1IDE2LjA1NS0zLjk1LTQuMTI1LTEuNDQ1IDEuMzg1IDUuMzcgNS42MSA5LjQ5NS05LjYtMS40Mi0xLjQwNXoiLz48L3N2Zz4=)}body #challenge-error-text{background-image:url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIzMiIgaGVpZ2h0PSIzMiIgZmlsbD0ibm9uZSI+PHBhdGggZmlsbD0iI0IyMEYwMyIgZD0iTTE2IDNhMTMgMTMgMCAxIDAgMTMgMTNBMTMuMDE1IDEzLjAxNSAwIDAgMCAxNiAzbTAgMjRhMTEgMTEgMCAxIDEgMTEtMTEgMTEuMDEgMTEuMDEgMCAwIDEtMTEgMTEiLz48cGF0aCBmaWxsPSIjQjIwRjAzIiBkPSJNMTcuMDM4IDE4LjYxNUgxNC44N0wxNC41NjMgOS41aDIuNzgzem0tMS4wODQgMS40MjdxLjY2IDAgMS4wNTcuMzg4LjQwNy4zODkuNDA3Ljk5NCAwIC41OTYtLjQwNy45ODQtLjM5Ny4zOS0xLjA1Ny4zODktLjY1IDAtMS4wNTYtLjM4OS0uMzk4LS4zODktLjM5OC0uOTg0IDAtLjU5Ny4zOTgtLjk...

https://on.cypress.io/request
      at <unknown> (http://localhost:43249/__cypress/runner/cypress_runner.js:139729:80)
      at tryCatcher (http://localhost:43249/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:43249/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (http://localhost:43249/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (http://localhost:43249/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:43249/__cypress/runner/cypress_runner.js:7031:18)
      at _drainQueueStep (http://localhost:43249/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue (http://localhost:43249/__cypress/runner/cypress_runner.js:3614:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:43249/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues (http://localhost:43249/__cypress/runner/cypress_runner.js:3500:14)
  From Your Spec Code:
      at visit (webpack:///./cypress/e2e/book-reservation.cy.ts:105:7)
      at Context.eval (webpack:///./cypress/e2e/book-reservation.cy.ts:158:8)

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 seconds                                                                        │
  │ Spec Ran:     book-reservation.cy.ts                                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

  (Screenshots)

  -  /home/ubuntu/tockstalk/cypress/screenshots/book-reservation.cy.ts/book reservati     (1280x720)
     on -- for first available time preference (failed).png                                         

  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
  -  Finished processing: 1 second                                                   

  -  Video output: /home/ubuntu/tockstalk/cypress/videos/book-reservation.cy.ts.mp4

====================================================================================================`

**Comment by daninger4995** [comment]
It appears that they use cloudflare turnstile, which nopecha says they can support, though my skillset here is not advanced enough to figure out how to implement it sadly.

**Comment by azoff** [comment]
So, I just pushed [v1.1.0](https://github.com/azoff/tockstalk/releases/tag/v1.1.0) which avoids this issue alltogether by preventing the runner from running in "studio" mode. I put [some notes in the README to explain why this works](https://github.com/azoff/tockstalk?tab=readme-ov-file#bot-detection). Should be good to go now :)
